# Generated by Django 3.1.3 on 2021-03-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetpropertyvalue',
            name='name',
        ),
    ]
