# Generated by Django 3.1.3 on 2021-03-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0002_remove_assetpropertyvalue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='assettypeproperty',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='assettypesymbol',
            name='symbol',
            field=models.ImageField(unique=True, upload_to='symbol_img/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
